### ISSUE TITLE
won't compile in arduino 1.0.5

### ISSUE THREAD

**Issue by jerkey** [sparkfun/OpenLog#171]
after setting up the latest libraries properly:

In file included from OpenLog_v3.ino:180:
/Users/possum/Documents/Arduino/libraries/SerialPort/SerialPort.h:194:2: error: #error Invalid SP_RX_BUF_OVERRUN bit
In constructor 'SerialPort<PortNumber, RxBufSize, TxBufSize>::SerialPort() [with unsigned char PortNumber = 0u, unsigned int RxBufSize = 750u, unsigned int TxBufSize = 0u]',
    inlined from 'void __static_initialization_and_destruction_0(int, int)' at OpenLog_v3.ino:184,
    inlined from '(static initializers for /Users/possum/Documents/Arduino/libraries/SerialPort/SerialPort.h)' at OpenLog_v3.ino:2507:
/Users/possum/Documents/Arduino/libraries/SerialPort/SerialPort.h:306: error: call to 'badPortNumber' declared with attribute error: Bad port number
