### ISSUE TITLE
Failed to compile in Arduino 1.6.5

### ISSUE THREAD

**Issue by woeileong1104** [sparkfun/OpenLog#213]
I intend to create a hex file and flash with Arduino ISP. I did everything according to instruction, but I get the following error messages when I try to export compiled binary. Appreciate some help, have been trying to make OpenLog works on a paparazzi UAV.

C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `PrintFile::write(unsigned char const*, unsigned int)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/ArduinoFiles.h:109: undefined reference to `FatFile::write(void const*, unsigned int)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::write(unsigned char)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:911: undefined reference to `FatFile::write(void const*, unsigned int)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::open(char const*, unsigned char)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:562: undefined reference to `FatFile::m_cwd'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:562: undefined reference to `FatFile::m_cwd'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:562: undefined reference to `FatFile::open(FatFile*, char const*, unsigned char)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::read()':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:682: undefined reference to `FatFile::read(void*, unsigned int)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::setCwd(FatFile*)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:812: undefined reference to `FatFile::m_cwd'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:812: undefined reference to `FatFile::m_cwd'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFileSystem::chdir(bool)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:113: undefined reference to `FatFile::close()'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:114: undefined reference to `FatFile::openRoot(FatVolume*)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFileSystem::chdir(char const*, bool)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:142: undefined reference to `FatFile::open(FatFile*, char const*, unsigned char)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `SdFat::begin(unsigned char, SPISettings)':
C:\Users\username\Documents\Arduino\libraries\src/SdFat.h:322: undefined reference to `SdSpiCard::begin(SdSpiAltDriver*, unsigned char, SPISettings)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFileSystem::begin(SdSpiCard*, unsigned char)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:46: undefined reference to `FatFile::close()'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:47: undefined reference to `FatVolume::init(unsigned char)'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:48: undefined reference to `FatFile::openRoot(FatVolume*)'
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:47: undefined reference to `FatVolume::init(unsigned char)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `newLog()':
C:\Program Files (x86)\Arduino/OpenLog.ino:335: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:338: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:349: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `recordConfigFile()':
C:\Program Files (x86)\Arduino/OpenLog.ino:941: undefined reference to `FatFile::remove()'
C:\Program Files (x86)\Arduino/OpenLog.ino:943: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:970: undefined reference to `FatFile::write(void const*, unsigned int)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::write(char const*)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:904: undefined reference to `FatFile::write(void const*, unsigned int)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `recordConfigFile()':
C:\Program Files (x86)\Arduino/OpenLog.ino:980: undefined reference to `FatFile::sync()'
C:\Program Files (x86)\Arduino/OpenLog.ino:981: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `readConfigFile()':
C:\Program Files (x86)\Arduino/OpenLog.ino:737: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:759: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `lsPrintNext(FatFile*, char*, unsigned char, unsigned char)':
C:\Program Files (x86)\Arduino/OpenLog.ino:2207: undefined reference to `FatFile::openNext(FatFile*, unsigned char)'
C:\Program Files (x86)\Arduino/OpenLog.ino:2210: undefined reference to `FatFile::getSFN(char*)'
C:\Program Files (x86)\Arduino/OpenLog.ino:2230: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:2263: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::rewind()':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:738: undefined reference to `FatFile::seekSet(unsigned long)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `lsPrint(FatFile*, char*, unsigned char, unsigned char)':
C:\Program Files (x86)\Arduino/OpenLog.ino:2159: undefined reference to `FatFile::open(FatFile*, unsigned int, unsigned char)'
C:\Program Files (x86)\Arduino/OpenLog.ino:2164: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFile::rewind()':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFile.h:738: undefined reference to `FatFile::seekSet(unsigned long)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `appendFile(char*)':
C:\Program Files (x86)\Arduino/OpenLog.ino:416: undefined reference to `FatFile::sync()'
C:\Program Files (x86)\Arduino/OpenLog.ino:456: undefined reference to `FatFile::sync()'
C:\Program Files (x86)\Arduino/OpenLog.ino:508: undefined reference to `FatFile::sync()'
C:\Program Files (x86)\Arduino/OpenLog.ino:525: undefined reference to `FatFile::sync()'
C:\Program Files (x86)\Arduino/OpenLog.ino:529: undefined reference to `FatFile::truncate(unsigned long)'
C:\Program Files (x86)\Arduino/OpenLog.ino:531: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `seqLog()':
C:\Program Files (x86)\Arduino/OpenLog.ino:393: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `FatFileSystem::mkdir(char const*, bool)':
C:\Users\username\Documents\Arduino\libraries\src/FatLib/FatFileSystem.h:229: undefined reference to `FatFile::mkdir(FatFile*, char const*, bool)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `commandShell()':
C:\Program Files (x86)\Arduino/OpenLog.ino:1293: undefined reference to `FatFile::seekSet(unsigned long)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1299: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1345: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1373: undefined reference to `FatFile::seekSet(unsigned long)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1420: undefined reference to `FatFile::write(void const*, unsigned int)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1423: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1435: undefined reference to `FatFile::close()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `SdSpiCard::readCID(CID*)':
C:\Users\username\Documents\Arduino\libraries\src/SdCard/SdSpiCard.h:130: undefined reference to `SdSpiCard::readRegister(unsigned char, void*)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `commandShell()':
C:\Program Files (x86)\Arduino/OpenLog.ino:1501: undefined reference to `SdSpiCard::cardSize()'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `SdSpiCard::readCSD(csd_t*)':
C:\Users\username\Documents\Arduino\libraries\src/SdCard/SdSpiCard.h:141: undefined reference to `SdSpiCard::readRegister(unsigned char, void*)'
C:\Users\username\AppData\Local\Temp\build79349827545308736.tmp\OpenLog.cpp.o: In function `commandShell()':
C:\Program Files (x86)\Arduino/OpenLog.ino:1539: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1179: undefined reference to `FatFile::open(FatFile*, char const*, unsigned char)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1181: undefined reference to `FatFile::rmRfStar()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1198: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1200: undefined reference to `FatFile::remove()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1191: undefined reference to `FatFile::open(FatFile*, char const*, unsigned char)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1195: undefined reference to `FatFile::rmdir()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1218: undefined reference to `FatFile::openNext(FatFile*, unsigned char)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1222: undefined reference to `FatFile::getSFN(char*)'
C:\Program Files (x86)\Arduino/OpenLog.ino:1226: undefined reference to `FatFile::close()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1229: undefined reference to `FatFile::remove()'
C:\Program Files (x86)\Arduino/OpenLog.ino:1236: undefined reference to `FatFile::close()'
collect2.exe: error: ld returned 1 exit status
Error compiling.

**Comment by woeileong1104** [comment]
Solved it. I didn't realize the libraries are attached, I actually downloaded latest libraries from Greiman. Just use the attached ones, compiled successfully.
